Add new detailed errors to executor.proto
0xPolygonHermez/zkevm-comms-protocol pull request #87
Opened 2023-08-18 13:38 UTC by fractasy

2023-08-18 14:32 UTC, ToniRamirezM approved these changes

2023-08-18 14:33 UTC, ToniRamirezM requested changes

2023-08-18 14:33 UTC, ToniRamirezM commented on proto/executor/v1/executor.proto
> +option go_package = "github.com/0xPolygonHermez/zkevm-node/state/runtime/executor/pb";
Do not make this change

2023-08-18 16:02 UTC, ToniRamirezM requested changes

2023-08-18 16:02 UTC, ToniRamirezM commented on proto/executor/v1/executor.proto
> +    // EXECUTOR_ERROR_SM_MAIN_HASHK_VALUE_MISMATCH indicates that the Keccak hash instruction check failed
Errors 38, 39 y 40 have the same description

2023-08-18 16:05 UTC, ToniRamirezM commented on proto/executor/v1/executor.proto
> +    // EXECUTOR_ERROR_SM_MAIN_HASHK_VALUE_MISMATCH indicates that the Keccak hash instruction check failed
The same for 46, 47 and 48

2023-08-21 07:42 UTC, fractasy commented on proto/executor/v1/executor.proto
> +option go_package = "github.com/0xPolygonHermez/zkevm-node/state/runtime/executor/pb";
Done

2023-08-21 07:42 UTC, fractasy commented on proto/executor/v1/executor.proto
> +    // EXECUTOR_ERROR_SM_MAIN_HASHK_VALUE_MISMATCH indicates that the Keccak hash instruction check failed
Fixed

2023-09-14 08:09 UTC, closed without merging

2023-09-14 08:09 UTC, fractasy commented
Using PR 88, which is a superset of this one.